apiVersion: v1
kind: Pod
metadata:
  name:  client-pod
  label:
    component: web
spec:
  containers:
    - name: client
      image: stephengrider/multi-client
      ports:
        - containerPort: 3000
      